### ISSUE TITLE
linphone sip account registration error on desktop

### ISSUE THREAD

**Issue by manisha-7222** [stevemao/github-issue-templates#16]
i have created an account using sip. when i try to connect it is showing error and also not able to doing calling. i do not know where i went wrong please help.
![linphone11](https://user-images.githubusercontent.com/30713994/65749262-6bc9c100-e123-11e9-92e2-9757d12407c0.png)

**Comment by stevemao** [comment]
Wrong repo

**Comment by manisha-7222** [comment]
please help me with correct one

**Comment by stevemao** [comment]
No idea what you're saying
