### ISSUE TITLE
Proposal / Request: Architecture Decision Record (ADR) template

### ISSUE THREAD

**Issue by FranzSkuffka** [stevemao/github-issue-templates#18]
For internal technical discussions about technology choices, the mADR template comes in helpful:
https://adr.github.io/madr/

What is planned on ADRs for this awesome collection of templates?

**Comment by stevemao** [comment]
Thanks for this. I don't know about madr and this repo is only for GitHub issue and PR templates. I don't know if adding it would increase the scope of this collection.
