### ISSUE TITLE
Add contributing guide + Issue templates

### ISSUE THREAD

**Issue by greydnls** [stevemao/github-issue-templates#25]
I noticed that this very useful repository of issue templates does not, itself, use any issue templates. I was going to open a PR to add issue templates, but I wasn't sure which ones you would want to use. That lead me to looking for a CONTRIBUTING.md or similar, which also doesn't exist. 

Happy to add both in a PR, if you'd like to point me towards which one you'd like used (or you can close this, if you'd rather not have either of those things)

**Comment by stevemao** [comment]
PR welcome!
