### ISSUE TITLE
 Mac OS ide-python Atom Package Not Working 

### ISSUE THREAD

**Issue by collmorg** [stevemao/github-issue-templates#28]
I am attempting to install this in the terminal to use a linter package titled "ide-python" in atom. When I run this: python -m pip install 'python-language-server[all]'

I receive the error:
ERROR: Could not find a version that satisfies the requirement ujson>=3.0.0 (from python-language-server[all]) (from versions: 1.4, 1.6, 1.8, 1.9, 1.15, 1.18, 1.19, 1.21, 1.22, 1.23, 1.30, 1.33, 1.34, 1.35, 2.0.0, 2.0.1, 2.0.2, 2.0.3)
ERROR: No matching distribution found for ujson>=3.0.0 (from python-language-server[all])

Please help as I am very new to coding and am not sure what is going on.

**Comment by stevemao** [comment]
Wrong repo?
