### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by Tomodachi94** [stevemao/github-issue-templates#34]
Hi,

Noticed your repo doesn’t have a license file.

This by default prevents people from doing *anything* with the content of this repo, as no license = All Rights Reserved. Please consider a license for this project.

**Comment by stevemao** [comment]
PR welcome

**Comment by Tomodachi94** [comment]
Noted, I’ll do that @stevemao

**Comment by Tomodachi94** [comment]
Done and done.
