### ISSUE TITLE
# Bug report

### ISSUE THREAD

**Issue by gummyg** [stevemao/github-issue-templates#39]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

__Originally posted by @gummyg in https://github.com/supabase/supabase/issues/1208__

**Comment by stevemao** [comment]
What is this?
